### ISSUE TITLE
Change jupyter-book version

### ISSUE THREAD

**Issue by lsetiawan** [uwhackweek/docker-template#2]
The environment file here has v0.8.2 of jupyter-book. Seems like jupyter-book is now at version 0.10.0 and our current `_config.yaml` uses the newer syntax.

https://github.com/uwhackweek/docker-template/blob/0fef9f3ecc3a252d06a3a281d17f9e284e0a835b/environment.yml#L28

**Comment by scottyhq** [comment]
good call. fixed by 3111a58
